asp_presentacion/Pages/Agenda.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages
{
    public class AgendaModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

asp_presentacion/Pages/Cuenta.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages
{
    public class CuentaModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

asp_presentacion/Pages/Emergentes/Mensajes.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages.Emergentes
{
    public class MensajescshtmlModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

asp_presentacion/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace asp_presentacion.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

asp_presentacion/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages
{
    public class Index1Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

asp_presentacion/Pages/Inicio.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages
{
    public class IndexModel : PageModel
    {
        
        
    }
}

asp_presentacion/Pages/MensajeExito.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages
{
    public class MensajeExitoModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

asp_presentacion/Pages/Perfil.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages
{
    public class PerfilModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

asp_presentacion/Pages/Registro.cshtml.cs
using lib_entidades.Modelos;
using lib_presentaciones.Interfaces;
using lib_utilidades;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages
{

    public class RegistroModel : PageModel
    {
        private IPacientePresentacion? iPresentacion = null;

        public RegistroModel(IPacientePresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Paciente();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Paciente? Actual { get; set; }
        [BindProperty] public Paciente? Filtro { get; set; }
        [BindProperty] public List<Paciente>? Lista { get; set; }

        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                var variable_session = HttpContext.Session.GetString("Usuario");
                if (String.IsNullOrEmpty(variable_session))
                {
                    HttpContext.Response.Redirect("/");
                    return;
                }
                Filtro!.Nombre = Filtro!.Nombre ?? "";

                Accion = Enumerables.Ventanas.Listas;
                var task = this.iPresentacion!.Buscar(Filtro!, "NOMBRE");
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Paciente();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Task<Paciente>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.GuardarPaciente(Actual!);
                else
                    task = this.iPresentacion!.Modificar(Actual!);
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

asp_presentacion/Pages/Agenda.cshtml
@page
@model asp_presentacion.Pages.AgendaModel
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/global.css" />
    <link rel="stylesheet" href="~/css/styleguideHC.css" />
    <link rel="stylesheet" href="~/css/styleAgenda.css" />
</head>
<body>
    <div class="historial-clinico">
        <div class="navbar">
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-home-2.svg" />
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-bell.svg" />
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-setting.svg" />
        </div>
        <div class="div">

            <a href="Inicio">
                <div class="arrow">
                    <img src="~/images/left-arrow.png" />
                </div>
            </a>
            <div class="overlap-2">
                <div class="horizontal-card">
                    <div class="your-diet-chart">Agenda</div>
                    <div class="illustration"></div>
                </div>
                <img class="image" src="https://c.animaapp.com/xuEWHKzq/img/image-35@2x.png" /> 
            </div>

            <div class="overlap-group">
                <div class="card-grid">
                    <div class="note-card">
                        <div class="today">Control</div>
                        <p class="div-2">Especialista: Internista</p>
                        <p class="div-2">Fecha: 15 de diciembre de 2022</p>
                        <p class="div-2">Hora: 5 p.m.</p>
                        <p class="div-2">Médico: Juan Pérez</p>
                    </div>
                </div>
                <div class="search-form-container">
                    <form method="post">
                        <button type="submit" class="search-button1" asp-page-handler="#">Eliminar</button>
                        <button type="submit" class="search-button2" asp-page-handler="#">Reprogramar</button>
                    </form>
                </div>
                <a href="#">
                    <div class="black-button">
                        <img src="~/images/plus.png" />
                    </div>
                </a>
            </div>
        </div>
    </div>
    
</body>
</html>

asp_presentacion/Pages/Cuenta.cshtml
@page
@model asp_presentacion.Pages.CuentaModel
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/global.css" />
    <link rel="stylesheet" href="~/css/styleguideHC.css" />
    <link rel="stylesheet" href="~/css/styleCuenta.css" />
</head>
<body>
    <div class="cuenta">
        <div class="navbar">
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-home-2.svg" />
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-bell.svg" />
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-setting.svg" />
        </div>
        <div class="div">
            <a href="Perfil">
                <div class="arrow">
                    <img src="~/images/left-arrow.png" />
                </div>
            </a>

            <div class="your-diet-chart">Cuenta</div>
            <div class="card-grid">
                <div class="note-card">
                    <ul>
                        <li class="li1"><div class="today">Datos personales</div>
                            <p class="div-2">Verifica tus datos personales</p>
                        </li>
                    </ul>
                </div>

                <div class="note-card">
                    <ul>
                        <li class="li2">
                            <div class="today">Tu información y tus permisos</div>
                            <p class="div-2">Accede a tu información, tu historial de citas y permisos autorizados</p>
                        </li>
                    </ul>
                </div>
                <a href="EditarPaciente">
                    <div class="note-card">
                    <ul>
                        <li class="li3">
                            <div class="today">Actualizar datos</div>
                            <p class="div-2">Cambia y completa los datos resultantes</p>
                        </li>
                    </ul>
                </div>
                </a>
            </div>      
        </div>
    </div>

</body>
</html>

asp_presentacion/Pages/EditarPaciente.cshtml
@page
@model asp_presentacion.Pages.EditarPacienteModel
@{
}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/global.css" />
    <link rel="stylesheet" href="~/css/styleguideHC.css" />
    <link rel="stylesheet" href="~/css/styleEditarPaciente.css" />
    <title>Actualizar Paciente</title>
</head>
<body>
    <div class="container">
        <div class="navbar">
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-home-2.svg" />
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-bell.svg" />
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-setting.svg" />
        </div>
        <div class="div">
            <a href="Cuenta">
                <div class="arrow">
                    <img src="~/images/left-arrow.png" />
                </div>
            </a>
            <div class="overlap-2">
                <div class="horizontal-card">
                    <div class="your-diet-chart">Actualizar datos</div>
                    <div class="illustration"></div>
                </div>
            </div>
            <div class="form-section">
                <form method="post">
                    <input type="hidden" asp-for="PacienteEditable.Id" />
                    <input type="hidden" asp-for="PacienteEditable.Cedula" />

                    <div class="input-card">
                        <label class="form-label" asp-for="PacienteEditable.Nombre">Nombre</label>
                        <input type="text" class="form-input" asp-for="PacienteEditable.Nombre" placeholder="Ingrese su nombre completo" required>
                        <span asp-validation-for="PacienteEditable.Nombre" class="text-danger"></span>
                    </div>

                    <div class="input-card">
                        <label class="form-label" asp-for="PacienteEditable.Telefono">Teléfono</label>
                        <input type="tel" class="form-input" asp-for="PacienteEditable.Telefono"
                                placeholder="Ingrese su número de teléfono Solo Numeros"
                                inputmode="numeric" pattern="[0-9]*" required>
                        <span asp-validation-for="PacienteEditable.Telefono" class="text-danger"></span>
                    </div>

                    <div class="input-card">
                        <label class="form-label" asp-for="PacienteEditable.TipoSang">Tipo de sangre</label>
                        <select class="form-input" asp-for="PacienteEditable.TipoSang" required>
                            <option value="">Seleccione un tipo</option>
                            <option value="A+">A+</option>
                            <option value="A-">A-</option>
                            <option value="B+">B+</option>
                            <option value="B-">B-</option>
                            <option value="AB+">AB+</option>
                            <option value="AB-">AB-</option>
                            <option value="O+">O+</option>
                            <option value="O-">O-</option>
                        </select>
                        <span asp-validation-for="PacienteEditable.TipoSang" class="text-danger"></span>
                    </div>

                    <div class="input-card">
                        <label class="form-label" asp-for="PacienteEditable.Email">Email</label>
                        <input type="email" class="form-input" asp-for="PacienteEditable.Email" placeholder="correo@ejemplo.com">
                        <span asp-validation-for="PacienteEditable.Email" class="text-danger"></span>
                    </div>

                    <div class="input-card">
                        <label class="form-label" asp-for="PacienteEditable.Acudiente">Acudiente</label>
                        <input type="text" class="form-input" asp-for="PacienteEditable.Acudiente" placeholder="Nombre del acudiente">
                        <span asp-validation-for="PacienteEditable.Acudiente" class="text-danger"></span>
                    </div>

                    <div class="input-card">
                        <label class="form-label" asp-for="PacienteEditable.eps">EPS</label>
                        <input type="text" class="form-input" asp-for="PacienteEditable.eps" placeholder="Entidad promotora de salud">
                        <span asp-validation-for="PacienteEditable.eps" class="text-danger"></span>
                    </div>


                    <button type="submit" class="search-button1">✔</button>


                        
                    
                </form>
            </div>

        </div>
    </div>
</body>

<script src="~/js/validarTipoSangre.js"></script>
<script src="~/js/validarTelefono.js"></script>
<script src="~/js/confirmarSalida.js"></script>
</html>

asp_presentacion/Pages/Emergentes/Mensajes.cshtml
}<center>
    <div class='popup'>
        <div class='pp_ms_inner'>
            <div style='width:95%'>
                <h2 align="left">
                    Mensaje
                </h2>

                <h4 align="left">
                    @ViewData["Mensaje"]
                </h4>

                <input type="submit"
                       value="Cerrar"
                       asp-page-handler="BtCerrar"
                       class="btn btn-secondary" />
            </div>
        </div>
    </div>
</center>

asp_presentacion/Pages/HistoriaClinica.cshtml
@page
@model asp_presentacion.Pages.HistoriaClinicaModel
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/global.css" />
    <link rel="stylesheet" href="~/css/styleguideHC.css" />
    <link rel="stylesheet" href="~/css/styleHC.css" />
</head>
<body>
    <div class="historial-clinico">
        <div class="navbar">
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-home-2.svg" />
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-bell.svg" />
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-setting.svg" />
        </div>
        <div class="div">
           
            <a href="Inicio">
                <div class="arrow">
                    <img src="~/images/left-arrow.png" />
                </div>
            </a>
            <div class="overlap-2">
                <div class="horizontal-card">
                    <div class="your-diet-chart">Historial clínico</div>
                    <div class="illustration"></div>
                </div>
                <img class="image" src="https://c.animaapp.com/47gfdr1M/img/image-33@2x.png" />

                <!-- Formulario -->
                <div class="search-form-container">
                    <form method="post">
                        <input type="text" class="search-input" asp-for="Filtro.Paciente.Cedula" placeholder="Buscar por cédula" required>
                        <button type="submit" class="search-button" asp-page-handler="Buscar">Buscar</button>
                    </form>
                </div>
            </div>

            <div class="overlap-group">

                @if (Model.ErrorConsulta)
                {
                    <div class="alert-error">
                        <p>Ha ocurrido un error.</p>
                        <p class="p2">Intentando recargar la información.</p>
                    </div>
                } else {
                    <!-- Mensaje de alerta -->
                    @if (Model.BusquedaRealizada == false && Model.Actual == null)
                    {

                    }
                    else if (Model.BusquedaRealizada == true && Model.Actual == null)
                    {
                        <div class="alert-warning1">No hay información disponible.</div>
                    
                    }else{

                        <div class="card-grid">
                            <div class="row">
                                <div class="note-card">
                                    <div class="today">Paciente</div>
                                    <p class="div-2">Nombre: @Model.Actual.Paciente?.Nombre</p>
                                    <p class="div-2">Cédula: @Model.Actual.Paciente?.Cedula</p>
                                    <p class="div-2">Dirección: @Model.Actual.Paciente?.Direccion</p>
                                    <p class="div-2">Teléfono: @Model.Actual.Paciente?.Telefono</p>
                                </div>

                                <div class="note-card">
                                    <p class="div-2">Email: @Model.Actual.Paciente?.Email</p>
                                    <p class="div-2">Tipo de Sangre: @Model.Actual.Paciente?.TipoSang</p>
                                    <p class="div-2">Acudiente: @Model.Actual.Paciente?.Acudiente</p>
                                    <p class="div-2">EPS: @Model.Actual.Paciente?.eps</p>
                                </div>
                            </div>

                            <div class="row-2">
                                <div class="note-card">
                                    <div class="today">Cita previa</div>
                                    @if (Model.Actual.Paciente?.Citas != null && Model.Actual.Paciente.Citas.Any())
                                    {
                                        var cita = Model.Actual.Paciente.Citas.First();
                                        <p class="div-2">Fecha: @cita.Fecha.ToString("dd/MM/yyyy")</p>
                                        <p class="div-2">Motivo: @cita.Motivo</p>
                                        <p class="div-2">Médico: @cita.Medico?.Nombre</p>
                                    }
                                    else
                                    {
                                        <p class="alert-warning">No se encontraron citas previas.</p>
                                    }
                                </div>

                                <div class="note-card">
                                    <div class="today">Diagnóstico</div>
                                    @if (Model.Actual.Diagnosticos != null && Model.Actual.Diagnosticos.Any())
                                    {
                                        var diag = Model.Actual.Diagnosticos.First();
                                        <p class="div-2">Descripción: @diag.Descripcion</p>
                                        <p class="div-2">Fecha: @diag.Fecha.ToString("dd/MM/yyyy")</p>
                                        <p class="div-2">Médico: @diag.Medico?.Nombre</p>
                                    }
                                    else
                                    {
                                        <p class="alert-warning">No se encontraron diagnósticos previos.</p>
                                    }
                                </div>
                            </div>

                            <div class="row-3">
                                <div class="note-card">
                                    <div class="today">Tratamiento</div>
                                    @if (Model.Actual.Tratamientos != null && Model.Actual.Tratamientos.Any())
                                    {
                                        var trat = Model.Actual.Tratamientos.First();
                                        <p class="div-2">Descripción: @trat.Descripcion</p>
                                        <p class="div-2">Fecha: @trat.FechaInicio.ToString("dd/MM/yyyy")</p>
                                    }
                                    else
                                    {
                                        <p class="alert-warning">No se encontraron tratamientos previos.</p>
                                    }
                                </div>

                                <div class="note-card">
                                    <div class="today">Fórmula</div>
                                    @if (Model.Actual.Formulas != null && Model.Actual.Formulas.Any())
                                    {
                                        var formula = Model.Actual.Formulas.First();
                                        if (formula.Medicamentos != null && formula.Medicamentos.Any())
                                        {
                                            var med = formula.Medicamentos.First();
                                            <p class="div-2">Medicamento: @med.Nombre</p>
                                            <p class="div-2">Dosis: @med.Dosis</p>
                                            <p class="div-2">Frecuencia: @med.Frecuencia</p>
                                        }
                                        else
                                        {
                                            <p class="alert-warning">No se encontraron medicamentos en la fórmula.</p>
                                        }
                                    }
                                    else
                                    {
                                        <p class="alert-warning">No se encontraron fórmulas previas.</p>
                                    }
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</body>
</html>

asp_presentacion/Pages/Index.cshtml
@page
@model asp_presentacion.Pages.Index1Model
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/global.css" />
    <link rel="stylesheet" href="~/css/styleguideHC.css" />
    <link rel="stylesheet" href="~/css/styleIndex.css" />
</head>
<body>
    <div class="index">
        <div class="div">
            <div class="overlap-group">
                <div class="card-grid">
                    <div class="today">Bienvenido</div>
                    <div class="today2">Mi Salud</div>
                </div>
            </div>
            <img class="logo" src="/images/logo.svg" />

            <div class="search-form-container">
                <button type="button" class="search-button1" role="link" onclick="window.location='Inicio'">Iniciar sesión</button>
                <button type="button" class="search-button1" role="link" onclick="window.location='Registro'">Crear cuenta</button>
            </div>

        </div>
    </div>

</body>
</html>

asp_presentacion/Pages/MensajeExito.cshtml
@page
@model asp_presentacion.Pages.MensajeExitoModel
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/global.css" />
    <link rel="stylesheet" href="~/css/styleguideHC.css" />
    <link rel="stylesheet" href="~/css/styleMensaje.css" />
</head>
<body>
    <div class="mensaje">
        <div class="navbar">
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-home-2.svg" />
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-bell.svg" />
            <img class="img" src="https://c.animaapp.com/xuEWHKzq/img/icon-setting.svg" />
        </div>
        <div class="div">

            <a href="EditarPaciente">
                <div class="arrow">
                    <img src="~/images/left-arrow.png" />
                </div>
            </a>

            <div class="overlap-group">
                <div class="card-grid">
                    <div class="today">Datos actualizados<br>con éxito</div>
                </div>

            </div>

            <a href="Cuenta">
                <div class="search-form-container">
                    <button type="button" class="search-button1">✔</button>
                </div>
            </a>
        </div>
    </div>

</body>
</html>

asp_presentacion/Pages/Registro.cshtml
@page
@model asp_presentacion.Pages.RegistroModel
@{
    
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MISALUD - Paciente</title>

    <!-- Favicon -->
    <link rel="icon" type="image/svg+xml" href="~/images/logo.svg">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/Registro.css">
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Regístrate</h1>
            <img src="~/images/logo.svg" alt="MISALUD Logo" class="logo">
        </div>


        <form id="registrationForm" method="post">
            @Html.AntiForgeryToken()

            <div class="form-group">
                <input type="text" class="form-control" asp-for="@Model.Actual!.Nombre" placeholder="Nombre completo" required>
            </div>

            <div class="form-group">
                <input type="text" class="form-control" asp-for="@Model.Actual!.Cedula" placeholder="Documento de identidad" required>
            </div>

            <div class="form-group">
                <input type="email" class="form-control" asp-for="@Model.Actual!.Email" placeholder="Email" required>
            </div>

            <div class="form-group">
                <div class="password-container">
                    <input type="password" class="form-control" placeholder="Contraseña" required>
                    <button type="button" class="password-toggle" id="togglePassword">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#1B6379" viewBox="0 0 16 16">
                            <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
                            <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
                        </svg>
                    </button>
                </div>
                <div class="forgot-password">
                    <a href="" id="forgotPassword">¿Olvidaste tu contraseña?</a>
                </div>
            </div>

            <div class="form-group">
                <button type="submit" class="btn" asp-page-handler="BtGuardar">Crear cuenta</button>

            </div>
        </form>

        <div class="form-footer">
            ¿Ya estás registrado? <a href="" id="iniciarSesion">Inicie sesión</a>
        </div>
    </div>

  
</body>
</html>